first_set = {
    "<program>": "seed",
    "<global>": ["floral"],
    "<constant>": ["hard"],
    "<statement>": [
        "tree",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
    ],
    "<filter-statement>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
    ],
    "<insert-variable>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<sqnc-type>": ["florist", "tulip", "dirt", "stem"],
    "<tint-value>": ["="],
    "<tint>": ["tint literal", "#", "lent", "tint", "flora literal", "flora", "("],
    "<tint-literals>": ["tint literal", "#", "lent", "tint"],
    "<flora-value>": ["="],
    "<flora>": ["flora literal", "flora", "tint literal", "#", "lent", "tint", "("],
    "<arithmetic>": [
        "tint literal",
        "#",
        "lent",
        "tint",
        "flora literal",
        "flora",
        "(",
    ],
    "<flora-literals>": [
        "flora literal",
        "flora",
        "tint literal",
        "#",
        "lent",
        "tint",
        "(",
    ],
    "<operate-number>": ["+", "-", "*", "/", "%"],
    "<operator>": ["+", "-", "*", "/", "%"],
    "<numerics>": ["tint literal", "#", "lent", "tint", "flora literal", "flora", "("],
    "<chard-value>": ["="],
    "<chard>": ["chard literal", "#", "chard"],
    "<string-value>": ["="],
    "<string>": ["string literal", "#", "string"],
    "<concatenate>": ["[", "+"],
    "<bloom-value>": ["="],
    "<bloom>": [
        "bloom literal",
        "bloom",
        "tint literal",
        "#",
        "lent",
        "tint",
        "flora literal",
        "flora",
        "(",
        "chard literal",
        "chard",
        "string literal",
        "string",
        "bare",
    ],
    "<bloom-literals>": [
        "bloom literal",
        "bloom",
        "tint literal",
        "#",
        "lent",
        "tint",
        "flora literal",
        "flora",
        "(",
        "chard literal",
        "chard",
        "string literal",
        "string",
        "bare",
    ],
    "<operate-logic>": ["=", "!", ">", "<", "at", "nut"],
    "<cond-operator>": ["=", "!", ">", "<", "at", "nut"],
    "<insert-func>": ["("],
    "<instance-grab>": ["."],
    "<indexing>": ["["],
    "<insert-index>": ["tint literal", "string literal"],
    "<more-tint>": [","],
    "<more-flora>": [","],
    "<more-chard>": [","],
    "<more-string>": [","],
    "<more-bloom>": [","],
    "<sqnc-value>": ["="],
    "<more-sqnc>": [","],
    "<more-id>": [","],
    "<sqnc>": [
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "#",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<supply-dirt>": ["getItems", "getKeys", "getValues"],
    "<open>": ["[", "{"],
    "<dirt>": ["string literal"],
    "<close>": ["]", "}"],
    "<sequence>": [
        "tint literal",
        "#",
        "lent",
        "tint",
        "flora literal",
        "flora",
        "(",
        "chard literal",
        "chard",
        "string literal",
        "string",
        "bloom literal",
        "bloom",
        "bare",
        "[",
        "{",
    ],
    "<common-data>": [
        "tint literal",
        "#",
        "lent",
        "tint",
        "flora literal",
        "flora",
        "(",
        "chard literal",
        "chard",
        "string literal",
        "string",
        "bloom literal",
        "bloom",
        "bare",
    ],
    "<next-sqnc>": [","],
    "<2D-sqnc>": [
        "tint literal",
        "#",
        "lent",
        "tint",
        "flora literal",
        "flora",
        "(",
        "chard literal",
        "chard",
        "string literal",
        "string",
        "bloom literal",
        "bloom",
        "bare",
        "[",
        "{",
    ],
    "<next-2D-sqnc>": [","],
    "<next-3D-sqnc>": [","],
    "<start-end-step>": ["["],
    "<insert-start>": ["tint literal", ":"],
    "<close-start>": ["]", ":", "tint literal"],
    "<close-end>": ["]", ":"],
    "<skip-start>": ["tint literal", ":"],
    "<2D-start-end-step>": ["["],
    "<2D-insert-start>": ["tint literal", ":"],
    "<2D-close-start>": ["]", ":", "tint literal"],
    "<2D-close-end>": ["]", ":"],
    "<2D-skip-start>": ["tint literal", ":"],
    "<3D-start-end-step>": ["["],
    "<3D-insert-start>": ["tint literal", ":"],
    "<3D-close-start>": ["]", ":", "tint literal"],
    "<3D-close-end>": ["]", ":"],
    "<3D-skip-start>": ["tint literal", ":"],
    "<all-type-value>": [
        "tint literal",
        "#",
        "lent",
        "tint",
        "flora literal",
        "flora",
        "(",
        "chard literal",
        "chard",
        "string literal",
        "string",
        "bloom literal",
        "bloom",
        "bare",
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
    ],
    "<i/o-statement>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "mint",
    ],
    "<insert-inpetal>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<common-type>": ["tint", "flora", "chard", "string", "bloom"],
    "<eleaf>": ["eleaf"],
    "<2D-eleaf>": ["eleaf"],
    "<3D-eleaf>": ["eleaf"],
    "<final-eleaf>": ["eleaf"],
    "<else>": ["moss"],
    "<2D-else>": ["moss"],
    "<3D-else>": ["moss"],
    "<final-else>": ["moss"],
    "<iterative>": ["fern", "willow"],
    "<insert-fern>": [
        "tint",
        "tint literal",
        "#",
        "lent",
        "flora literal",
        "flora",
        "(",
        "chard literal",
        "chard",
        "string literal",
        "string",
        "bloom literal",
        "bloom",
        "bare",
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
    ],
    "<assignment-op>": ["=", "+", "-", "*", "/", "%"],
    "<more-value>": [","],
    "<final-value>": [","],
    "<use-tree>": ["tree"],
    "<check-branch>": [
        "tint literal",
        "#",
        "lent",
        "tint",
        "flora literal",
        "flora",
        "(",
        "chard literal",
        "chard",
        "string literal",
        "string",
        "bloom literal",
        "bloom",
        "bare",
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
        "_",
    ],
    "<insert-branch>": [":", "leaf"],
    "<more-branch>": ["branch"],
    "<2D-statement>": [
        "tree",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
    ],
    "<use-2D-tree>": ["tree"],
    "<check-2D-branch>": [
        "tint literal",
        "#",
        "lent",
        "tint",
        "flora literal",
        "flora",
        "(",
        "chard literal",
        "chard",
        "string literal",
        "string",
        "bloom literal",
        "bloom",
        "bare",
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
        "_",
    ],
    "<insert-2D-branch>": [":", "leaf"],
    "<more-2D-branch>": ["branch"],
    "<filter-2D-state>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
    ],
    "<2D-iterative>": ["fern", "willow"],
    "<insert-2D-fern>": [
        "tint",
        "tint literal",
        "#",
        "lent",
        "flora literal",
        "flora",
        "(",
        "chard literal",
        "chard",
        "string literal",
        "string",
        "bloom literal",
        "bloom",
        "bare",
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
    ],
    "<3D-statement>": [
        "tree",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
    ],
    "<use-3D-tree>": ["tree"],
    "<check-3D-branch>": [
        "tint literal",
        "#",
        "lent",
        "tint",
        "flora literal",
        "flora",
        "(",
        "chard literal",
        "chard",
        "string literal",
        "string",
        "bloom literal",
        "bloom",
        "bare",
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
        "_",
    ],
    "<insert-3D-branch>": [":", "leaf"],
    "<more-3D-branch>": ["branch"],
    "<filter-3D-state>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
    ],
    "<3D-iterative>": ["fern", "willow"],
    "<insert-3D-fern>": [
        "tint",
        "tint literal",
        "#",
        "lent",
        "flora literal",
        "flora",
        "(",
        "chard literal",
        "chard",
        "string literal",
        "string",
        "bloom literal",
        "bloom",
        "bare",
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
    ],
    "<final-statement>": [
        "tree",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
    ],
    "<use-final-tree>": ["tree"],
    "<check-final-branch>": [
        "tint literal",
        "#",
        "lent",
        "tint",
        "flora literal",
        "flora",
        "(",
        "chard literal",
        "chard",
        "string literal",
        "string",
        "bloom literal",
        "bloom",
        "bare",
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
        "_",
    ],
    "<insert-final-branch>": [":", "leaf"],
    "<more-final-branch>": ["branch"],
    "<filter-final-state>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
    ],
    "<argument>": [
        "tint literal",
        "#",
        "lent",
        "tint",
        "flora literal",
        "flora",
        "(",
        "chard literal",
        "chard",
        "string literal",
        "string",
        "bloom literal",
        "bloom",
        "bare",
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
    ],
    "<insert-argument>": [
        "tint literal",
        "#",
        "lent",
        "tint",
        "flora literal",
        "flora",
        "(",
        "chard literal",
        "chard",
        "string literal",
        "string",
        "bloom literal",
        "bloom",
        "bare",
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
    ],
    "<insert**kwargs>": ["tint", "flora", "chard", "string", "bloom"],
    "<more**kwargs>": [","],
    "<add-argument>": [","],
    "<2D-argument>": [
        "tint literal",
        "#",
        "lent",
        "tint",
        "flora literal",
        "flora",
        "(",
        "chard literal",
        "chard",
        "string literal",
        "string",
        "bloom literal",
        "bloom",
        "bare",
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
    ],
    "<add-2D-argument>": [","],
    "<add-3D-argument>": [","],
    "<function>": ["tint", "flora", "chard", "string", "bloom", "viola"],
    "<add-at>": [",", "at"],
    "<common-variable>": ["tint", "flora", "chard", "string", "bloom"],
    "<parameter>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<undefined-param>": ["tint", "flora", "chard", "string", "bloom"],
    "<add-kwargs>": [","],
    "<next-parameter>": [","],
    "<2D-parameter>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<next-2D-param>": [","],
    "<3D-parameter>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<next-3D-param>": [","],
}
